authors = ["Huang, Jiangyi <jiangyi.huang@outlook.com>"]

[deps]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "â‰¥ 1.6"
